# Global Settings
title: "Snowflake Activation Team Resources"
description: "The place to review commonly used scripts, tutorials, and great to have info about getting up and running on Snowflake."

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons